services:
  biblioteca:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  
    restart: unless-stopped
    container_name: biblioteca-playground
